export const basicPronouns = [
  { term: "I (am)", translation: "я (є)" },
  { term: "you (are)", translation: "ти / ви (є)" },
  { term: "he (is)", translation: "він (є)" },
  { term: "she (is)", translation: "вона (є)" },
  { term: "it (is)", translation: "воно / це (є)" },
  { term: "we (are)", translation: "ми (є)" },
  { term: "they (are)", translation: "вони (є)" },
];

export const possessiveAdjectives = [
  { term: "my", translation: "мій, моя, моє, мої" },
  {
    term: "your",
    translation: "твій, твоя, твоє, твої / ваш, ваша, ваше, ваші",
  },
  { term: "his", translation: "його (чоловічий рід)" },
  { term: "her", translation: "її" },
  { term: "its", translation: "його, її (для предметів, тварин)" },
  { term: "our", translation: "наш, наша, наше, наші" },
  { term: "their", translation: "їхній, їхня, їхнє, їхні" },
];

export const objectPronouns = [
  { term: "me", translation: "мене, мені, мною" },
  { term: "you", translation: "тебе, тобі, вами, вас" },
  { term: "him", translation: "його, йому, ним" },
  { term: "her", translation: "її, їй, нею" },
  { term: "it", translation: "його, йому, ним (для предметів, тварин)" },
  { term: "us", translation: "нас, нам, нами" },
  { term: "them", translation: "їх, їм, ними" },
];

export const basicVerbs = [
  { term: "have", translation: "мати" },
  { term: "want", translation: "хотіти, бажати" },
  { term: "know", translation: "знати" },
  { term: "do", translation: "робити" },
  { term: "make", translation: "створювати, робити" },
  { term: "take", translation: "брати, приймати" },
  { term: "can / be able to", translation: "могти / бути здатним" },
  { term: "work", translation: "працювати" },
  { term: "buy", translation: "купувати" },
  { term: "get", translation: "отримувати, ставати, діставати" },
  { term: "use", translation: "використовувати" },
  { term: "go", translation: "йти, їхати" },
  { term: "come", translation: "приходити" },
  { term: "leave", translation: "залишати, йти, покидати" },
  { term: "stop", translation: "зупинятися, припиняти" },
  { term: "exit / go out", translation: "виходити" },
  { term: "come through", translation: "проходити, справлятися" },
  { term: "understand", translation: "розуміти" },
  { term: "speak", translation: "говорити" },
  { term: "say", translation: "казати" },
  { term: "ask", translation: "питати, просити" },
  { term: "eat", translation: "їсти" },
  { term: "drink", translation: "пити" },
  { term: "see", translation: "бачити" },
  { term: "look", translation: "дивитися, виглядати" },
  { term: "show", translation: "показувати" },
  { term: "like", translation: "подобатися, любити" },
  { term: "remember", translation: "пам’ятати" },
  { term: "forget", translation: "забувати" },
  { term: "read", translation: "читати" },
  { term: "write", translation: "писати" },
  { term: "keep", translation: "зберігати" },
  { term: "leave", translation: "залишати" },
  { term: "stay", translation: "залишатися, перебувати" },
];

export const questionWords = [
  { term: "who", translation: "хто" },
  { term: "what", translation: "що, який" },
  { term: "why", translation: "чому, навіщо" },
  { term: "where", translation: "де, куди" },
  { term: "when", translation: "коли" },
  { term: "which", translation: "який (з обмеженого вибору)" },
  { term: "whose", translation: "чий" },
  { term: "how", translation: "як" },
  { term: "how long", translation: "як довго" },
  { term: "what time", translation: "о котрій (годині)" },
  { term: "until what time", translation: "до котрої години" },
];

export const adverbsAndPhrases = [
  { term: "yes", translation: "так" },
  { term: "no", translation: "ні" },
  { term: "thanks", translation: "дякую" },
  { term: "please", translation: "будь ласка" },
  { term: "maybe", translation: "можливо" },
  { term: "ain’t it?", translation: "чи не так?, правда ж?" },
  { term: "here / there", translation: "тут / там" },
  { term: "now / right now", translation: "зараз / прямо зараз" },
  { term: "shame on you", translation: "сором тобі" },
  { term: "let’s see", translation: "давай подивимось, ну що ж" },
  { term: "only", translation: "тільки, лише" },
  { term: "for now", translation: "поки що" },
  { term: "later", translation: "пізніше" },
  { term: "before / after", translation: "до / після" },
  { term: "right / to the right", translation: "право / направо" },
  { term: "left / to the left", translation: "ліво / наліво" },
  { term: "today", translation: "сьогодні" },
  { term: "tomorrow", translation: "завтра" },
  { term: "yesterday", translation: "вчора" },
  { term: "a lot / many", translation: "багато" },
  { term: "little / few", translation: "мало (незлічувальні / злічувальні)" },
  { term: "then", translation: "тоді, потім" },
  { term: "unfortunately", translation: "на жаль" },
  { term: "everything", translation: "все" },
  { term: "nothing", translation: "нічого" },
  { term: "more", translation: "більше" },
  { term: "another", translation: "ще один, інший" },
  { term: "the rest", translation: "решта" },
  { term: "together", translation: "разом" },
  { term: "separately", translation: "окремо" },
];

export const adjectives = [
  { term: "big", translation: "великий" },
  { term: "medium", translation: "середній" },
  { term: "small", translation: "маленький" },
  { term: "other", translation: "інший" },
  { term: "same", translation: "той самий, однаковий" },
  { term: "open", translation: "відкритий" },
  { term: "closed", translation: "закритий" },
  { term: "far", translation: "далекий, далеко" },
  { term: "near", translation: "близький, поруч" },
  { term: "the first", translation: "перший" },
  { term: "the last", translation: "останній" },
  { term: "the next", translation: "наступний" },
  { term: "previous", translation: "попередній" },
  { term: "drunk", translation: "п’яний" },
  { term: "sober", translation: "тверезий" },
];
