export const phrasesCards = [
  {
    number: 1,
    phrases: [
      { term: "to get up", translation: "вставати" },
      { term: "to wake up", translation: "прокидатися" },
      { term: "to go to bed", translation: "лягати спати" },
      { term: "to go to work", translation: "йти на роботу" },
      { term: "to come home", translation: "повертатися додому" },
      { term: "to take a shower", translation: "приймати душ" },
      { term: "to brush teeth", translation: "чистити зуби" },
      { term: "to get dressed", translation: "одягатися" },
      { term: "to have breakfast", translation: "снідати" },
      { term: "to have lunch", translation: "обідати" },
      { term: "to have dinner", translation: "вечеряти" },
      { term: "to make dinner", translation: "готувати вечерю" },
      { term: "to cook food", translation: "готувати їжу" },
      { term: "to drink coffee", translation: "пити каву" },
      { term: "to drink water", translation: "пити воду" },
    ],
  },
  {
    number: 2,
    phrases: [
      { term: "to go shopping", translation: "ходити за покупками" },
      { term: "to buy groceries", translation: "купувати продукти" },
      { term: "to pay bills", translation: "платити рахунки" },
      { term: "to use a phone", translation: "користуватися телефоном" },
      { term: "to check messages", translation: "перевіряти повідомлення" },
      { term: "to watch TV", translation: "дивитися телевізор" },
      { term: "to watch a movie", translation: "дивитися фільм" },
      { term: "to listen to music", translation: "слухати музику" },
      { term: "to read a book", translation: "читати книгу" },
      { term: "to play games", translation: "грати в ігри" },
      { term: "to use a computer", translation: "користуватися комп'ютером" },
      { term: "to work from home", translation: "працювати з дому" },
      { term: "to go outside", translation: "виходити на вулицю" },
      { term: "to take a walk", translation: "йти гуляти" },
      { term: "to spend time", translation: "проводити час" },
    ],
  },
  {
    number: 3,
    phrases: [
      { term: "to meet friends", translation: "зустрічатися з друзями" },
      { term: "to talk to someone", translation: "говорити з кимось" },
      { term: "to call someone", translation: "дзвонити комусь" },
      { term: "to send a message", translation: "надсилати повідомлення" },
      { term: "to ask a question", translation: "задавати питання" },
      { term: "to answer a question", translation: "відповідати на питання" },
      { term: "to help someone", translation: "допомагати комусь" },
      { term: "to wait for someone", translation: "чекати когось" },
      { term: "to look for something", translation: "шукати щось" },
      { term: "to find something", translation: "знаходити щось" },
      { term: "to feel good", translation: "почуватися добре" },
      { term: "to feel tired", translation: "відчувати втому" },
      { term: "to feel happy", translation: "відчувати щастя" },
      { term: "to feel bad", translation: "почуватися погано" },
      { term: "to be in a hurry", translation: "поспішати" },
    ],
  },
  {
    number: 4,
    phrases: [
      { term: "to be late", translation: "запізнюватися" },
      { term: "to be early", translation: "приходити рано" },
      { term: "to be ready", translation: "бути готовим" },
      { term: "to be busy", translation: "бути зайнятим" },
      { term: "to be free", translation: "бути вільним" },
      { term: "to start work", translation: "починати роботу" },
      { term: "to finish work", translation: "закінчувати роботу" },
      { term: "to take a break", translation: "робити перерву" },
      { term: "to have a rest", translation: "відпочивати" },
      { term: "to go on vacation", translation: "йти у відпустку" },
      { term: "to travel abroad", translation: "подорожувати за кордон" },
      { term: "to book a hotel", translation: "забронювати готель" },
      { term: "to buy tickets", translation: "купувати квитки" },
      { term: "to miss a bus", translation: "пропустити автобус" },
      { term: "to catch a bus", translation: "встигнути на автобус" },
    ],
  },
  {
    number: 5,
    phrases: [
      { term: "to drive a car", translation: "водити машину" },
      { term: "to take a taxi", translation: "взяти таксі" },
      {
        term: "to use public transport",
        translation: "користуватися транспортом",
      },
      { term: "to open a door", translation: "відкрити двері" },
      { term: "to close a door", translation: "закрити двері" },
      { term: "to turn on", translation: "увімкнути" },
      { term: "to turn off", translation: "вимкнути" },
      { term: "to sit down", translation: "сісти" },
      { term: "to stand up", translation: "встати" },
      { term: "to lie down", translation: "лягти" },
      { term: "to clean the house", translation: "прибирати будинок" },
      { term: "to wash dishes", translation: "мити посуд" },
      { term: "to do laundry", translation: "прати" },
      { term: "to iron clothes", translation: "прасувати одяг" },
      { term: "to fix something", translation: "ремонтувати щось" },
    ],
  },
  {
    number: 6,
    phrases: [
      { term: "to build something", translation: "будувати щось" },
      { term: "to use tools", translation: "користуватися інструментами" },
      { term: "to carry something", translation: "нести щось" },
      { term: "to move something", translation: "переміщати щось" },
      { term: "to drop something", translation: "впустити щось" },
      { term: "to learn English", translation: "вчити англійську" },
      { term: "to study hard", translation: "старанно вчитися" },
      { term: "to do homework", translation: "робити домашнє завдання" },
      { term: "to take notes", translation: "робити нотатки" },
      { term: "to remember something", translation: "пам'ятати щось" },
      { term: "to forget something", translation: "забувати щось" },
      { term: "to understand", translation: "розуміти" },
      { term: "to explain", translation: "пояснювати" },
      { term: "to repeat", translation: "повторювати" },
      { term: "to practice", translation: "практикуватися" },
    ],
  },
  {
    number: 7,
    phrases: [
      { term: "to try something", translation: "пробувати щось" },
      { term: "to decide", translation: "вирішувати" },
      { term: "to plan something", translation: "планувати щось" },
      { term: "to change something", translation: "змінювати щось" },
      { term: "to improve", translation: "покращувати" },
      { term: "to increase", translation: "збільшувати" },
      { term: "to decrease", translation: "зменшувати" },
      { term: "to use something", translation: "використовувати щось" },
      { term: "to need something", translation: "потребувати щось" },
      { term: "to want something", translation: "хотіти щось" },
      { term: "to like something", translation: "подобатися щось" },
      { term: "to love something", translation: "любити щось" },
      { term: "to hate something", translation: "ненавидіти щось" },
      { term: "to enjoy something", translation: "насолоджуватися чимось" },
      { term: "to prefer something", translation: "надавати перевагу" },
    ],
  },
  {
    number: 8,
    phrases: [
      { term: "to choose something", translation: "обирати щось" },
      { term: "to pick something", translation: "вибирати щось" },
      { term: "to order food", translation: "замовляти їжу" },
      { term: "to eat outside", translation: "їсти поза домом" },
      { term: "to cook at home", translation: "готувати вдома" },
      { term: "to take responsibility", translation: "брати відповідальність" },
      { term: "to make a decision", translation: "приймати рішення" },
      { term: "to solve a problem", translation: "вирішувати проблему" },
      { term: "to deal with something", translation: "мати справу з чимось" },
      { term: "to depend on", translation: "залежати від" },
      { term: "to be responsible for", translation: "відповідати за" },
      { term: "to be interested in", translation: "цікавитися" },
      { term: "to be afraid of", translation: "боятися" },
      { term: "to be proud of", translation: "пишатися" },
      { term: "to be tired of", translation: "втомитися від" },
    ],
  },
  {
    number: 9,
    phrases: [
      { term: "to get used to", translation: "звикати до" },
      { term: "to look forward to", translation: "чекати з нетерпінням" },
      { term: "to take part in", translation: "брати участь" },
      { term: "to pay attention", translation: "звертати увагу" },
      { term: "to keep in mind", translation: "мати на увазі" },
      { term: "to come up with", translation: "придумати" },
      { term: "to find out", translation: "з'ясувати" },
      { term: "to figure out", translation: "розібратися" },
      { term: "to work on something", translation: "працювати над чимось" },
      { term: "to focus on", translation: "зосереджуватись на" },
      { term: "to run out of", translation: "закінчитися" },
      { term: "to get along with", translation: "ладити з" },
      { term: "to break down", translation: "ламатися" },
      { term: "to give up", translation: "здаватися" },
      { term: "to carry on", translation: "продовжувати" },
    ],
  },
  {
    number: 10,
    phrases: [
      { term: "to set up", translation: "налаштовувати / створювати" },
      { term: "to turn out", translation: "виявитися" },
      { term: "to bring up", translation: "піднімати тему" },
      { term: "to go through", translation: "переживати (складне)" },
      { term: "to take over", translation: "переймати контроль" },
      { term: "to keep going", translation: "продовжувати рухатися" },
      { term: "to slow down", translation: "сповільнюватися" },
      { term: "to speed up", translation: "прискорюватися" },
      { term: "to calm down", translation: "заспокоїтися" },
      { term: "to cheer up", translation: "підбадьоритися" },
      { term: "to grow up", translation: "дорослішати" },
      { term: "to end up", translation: "врешті опинитися" },
      { term: "to show up", translation: "з'явитися" },
      { term: "to come back", translation: "повертатися" },
      { term: "to go back", translation: "повертатися назад" },
    ],
  },
  {
    number: 11,
    phrases: [
      { term: "to take care of", translation: "піклуватися про" },
      { term: "to look after", translation: "доглядати" },
      { term: "to take into account", translation: "враховувати" },
      { term: "to make sure", translation: "переконатися" },
      { term: "to be aware of", translation: "усвідомлювати" },
      { term: "to be familiar with", translation: "бути знайомим з" },
      { term: "to be used to", translation: "бути звиклим до" },
      { term: "to be capable of", translation: "бути здатним до" },
      { term: "to be in charge of", translation: "бути відповідальним за" },
      { term: "to be involved in", translation: "бути залученим" },
      { term: "to take a risk", translation: "ризикувати" },
      { term: "to miss a chance", translation: "втратити шанс" },
      { term: "to make progress", translation: "робити прогрес" },
      { term: "to reach a goal", translation: "досягати цілі" },
      { term: "to set a goal", translation: "ставити ціль" },
    ],
  },
  {
    number: 12,
    phrases: [
      { term: "to achieve success", translation: "досягати успіху" },
      { term: "to face a problem", translation: "зіткнутися з проблемою" },
      { term: "to avoid mistakes", translation: "уникати помилок" },
      { term: "to learn from mistakes", translation: "вчитися на помилках" },
      { term: "to improve skills", translation: "покращувати навички" },
      { term: "to waste time", translation: "марнувати час" },
      { term: "to save time", translation: "економити час" },
      { term: "to spend money", translation: "витрачати гроші" },
      { term: "to save money", translation: "заощаджувати гроші" },
      { term: "to earn money", translation: "заробляти гроші" },
      { term: "to lose money", translation: "втрачати гроші" },
      { term: "to invest money", translation: "інвестувати гроші" },
      { term: "to borrow money", translation: "позичати гроші" },
      { term: "to lend money", translation: "позичати (комусь)" },
      { term: "to pay back", translation: "повертати борг" },
    ],
  },
  {
    number: 13,
    phrases: [
      { term: "to take notes", translation: "робити нотатки" },
      { term: "to give advice", translation: "давати пораду" },
      { term: "to follow advice", translation: "слідувати пораді" },
      { term: "to ask for help", translation: "просити допомогу" },
      { term: "to offer help", translation: "пропонувати допомогу" },
      { term: "to accept help", translation: "приймати допомогу" },
      { term: "to refuse help", translation: "відмовлятися від допомоги" },
      { term: "to give an example", translation: "наводити приклад" },
      { term: "to explain clearly", translation: "чітко пояснювати" },
      { term: "to speak fluently", translation: "говорити вільно" },
      { term: "to think about", translation: "думати про" },
      { term: "to think of", translation: "вигадати / згадати" },
      { term: "to believe in", translation: "вірити в" },
      { term: "to agree with", translation: "погоджуватися з" },
      { term: "to disagree with", translation: "не погоджуватися" },
    ],
  },
  {
    number: 14,
    phrases: [
      { term: "to argue with", translation: "сперечатися" },
      { term: "to complain about", translation: "скаржитися на" },
      { term: "to worry about", translation: "хвилюватися про" },
      { term: "to care about", translation: "піклуватися про" },
      { term: "to talk about", translation: "говорити про" },
      { term: "to get better", translation: "ставати кращим" },
      { term: "to get worse", translation: "ставати гіршим" },
      { term: "to get ready", translation: "готуватися" },
      { term: "to get started", translation: "почати" },
      { term: "to get tired", translation: "втомлюватися" },
      { term: "to get angry", translation: "злитися" },
      { term: "to get excited", translation: "хвилюватися (позитивно)" },
      { term: "to get bored", translation: "нудьгувати" },
      { term: "to get lost", translation: "загубитися" },
      { term: "to get married", translation: "одружитися" },
    ],
  },
];
