export const irregularVerbs = [
  {
    infinitive: "arise",
    past: "arose",
    participle: "arisen",
    translation: "з’являтися",
  },
  {
    infinitive: "awake",
    past: "awoke",
    participle: "awoken",
    translation: "прокидатися",
  },
  {
    infinitive: "bear",
    past: "bore",
    participle: "borne",
    translation: "терпіти, нести",
  },
  {
    infinitive: "beat",
    past: "beat",
    participle: "beaten",
    translation: "бити",
  },
  {
    infinitive: "become",
    past: "became",
    participle: "become",
    translation: "ставати",
  },
  {
    infinitive: "begin",
    past: "began",
    participle: "begun",
    translation: "починати",
  },
  {
    infinitive: "bend",
    past: "bent",
    participle: "bent",
    translation: "нахиляти, згинати",
  },
  {
    infinitive: "bet",
    past: "bet",
    participle: "bet",
    translation: "ставити (парі)",
  },
  {
    infinitive: "bid",
    past: "bid",
    participle: "bid",
    translation: "пропонувати, торгуватися",
  },
  {
    infinitive: "bind",
    past: "bound",
    participle: "bound",
    translation: "зв’язувати",
  },
  {
    infinitive: "bite",
    past: "bit",
    participle: "bitten",
    translation: "кусати",
  },
  {
    infinitive: "bleed",
    past: "bled",
    participle: "bled",
    translation: "кровоточити",
  },
  {
    infinitive: "blow",
    past: "blew",
    participle: "blown",
    translation: "дути",
  },
  {
    infinitive: "break",
    past: "broke",
    participle: "broken",
    translation: "ламати",
  },
  {
    infinitive: "breed",
    past: "bred",
    participle: "bred",
    translation: "розводити, виводити",
  },
  {
    infinitive: "bring",
    past: "brought",
    participle: "brought",
    translation: "приносити",
  },
  {
    infinitive: "build",
    past: "built",
    participle: "built",
    translation: "будувати",
  },
  {
    infinitive: "burn",
    past: "burnt",
    participle: "burnt",
    translation: "палити, горіти",
  },
  {
    infinitive: "burst",
    past: "burst",
    participle: "burst",
    translation: "вибухати, лопатися",
  },
  {
    infinitive: "buy",
    past: "bought",
    participle: "bought",
    translation: "купувати",
  },
  {
    infinitive: "cast",
    past: "cast",
    participle: "cast",
    translation: "кидати",
  },
  {
    infinitive: "catch",
    past: "caught",
    participle: "caught",
    translation: "ловити",
  },
  {
    infinitive: "choose",
    past: "chose",
    participle: "chosen",
    translation: "вибирати",
  },
  {
    infinitive: "cling",
    past: "clung",
    participle: "clung",
    translation: "чіплятися",
  },
  {
    infinitive: "come",
    past: "came",
    participle: "come",
    translation: "приходити",
  },
  {
    infinitive: "cost",
    past: "cost",
    participle: "cost",
    translation: "коштувати",
  },
  {
    infinitive: "creep",
    past: "crept",
    participle: "crept",
    translation: "повзти",
  },
  { infinitive: "cut", past: "cut", participle: "cut", translation: "різати" },
  {
    infinitive: "deal",
    past: "dealt",
    participle: "dealt",
    translation: "мати справу, роздавати",
  },
  { infinitive: "dig", past: "dug", participle: "dug", translation: "копати" },
  { infinitive: "do", past: "did", participle: "done", translation: "робити" },
  {
    infinitive: "draw",
    past: "drew",
    participle: "drawn",
    translation: "малювати, тягнути",
  },
  {
    infinitive: "dream",
    past: "dreamt",
    participle: "dreamt",
    translation: "мріяти",
  },
  {
    infinitive: "drink",
    past: "drank",
    participle: "drunk",
    translation: "пити",
  },
  {
    infinitive: "drive",
    past: "drove",
    participle: "driven",
    translation: "їхати, водити",
  },
  { infinitive: "eat", past: "ate", participle: "eaten", translation: "їсти" },
  {
    infinitive: "fall",
    past: "fell",
    participle: "fallen",
    translation: "падати",
  },
  {
    infinitive: "feed",
    past: "fed",
    participle: "fed",
    translation: "годувати",
  },
  {
    infinitive: "feel",
    past: "felt",
    participle: "felt",
    translation: "відчувати",
  },
  {
    infinitive: "fight",
    past: "fought",
    participle: "fought",
    translation: "боротися",
  },
  {
    infinitive: "find",
    past: "found",
    participle: "found",
    translation: "знаходити",
  },
  {
    infinitive: "flee",
    past: "fled",
    participle: "fled",
    translation: "тікати",
  },
  {
    infinitive: "fly",
    past: "flew",
    participle: "flown",
    translation: "летіти",
  },
  {
    infinitive: "forbid",
    past: "forbade",
    participle: "forbidden",
    translation: "забороняти",
  },
  {
    infinitive: "forget",
    past: "forgot",
    participle: "forgotten",
    translation: "забувати",
  },
  {
    infinitive: "forgive",
    past: "forgave",
    participle: "forgiven",
    translation: "прощати",
  },
  {
    infinitive: "freeze",
    past: "froze",
    participle: "frozen",
    translation: "замерзати",
  },
  {
    infinitive: "get",
    past: "got",
    participle: "got",
    translation: "отримувати",
  },
  {
    infinitive: "give",
    past: "gave",
    participle: "given",
    translation: "давати",
  },
  { infinitive: "go", past: "went", participle: "gone", translation: "йти" },
  {
    infinitive: "grind",
    past: "ground",
    participle: "ground",
    translation: "молоти",
  },
  {
    infinitive: "grow",
    past: "grew",
    participle: "grown",
    translation: "рости",
  },
  {
    infinitive: "hang",
    past: "hung",
    participle: "hung",
    translation: "вішати",
  },
  { infinitive: "have", past: "had", participle: "had", translation: "мати" },
  {
    infinitive: "hear",
    past: "heard",
    participle: "heard",
    translation: "чути",
  },
  {
    infinitive: "hide",
    past: "hid",
    participle: "hidden",
    translation: "ховати(ся)",
  },
  { infinitive: "hit", past: "hit", participle: "hit", translation: "вдаряти" },
  {
    infinitive: "hold",
    past: "held",
    participle: "held",
    translation: "тримати",
  },
  {
    infinitive: "hurt",
    past: "hurt",
    participle: "hurt",
    translation: "ранити, боліти",
  },
  {
    infinitive: "keep",
    past: "kept",
    participle: "kept",
    translation: "зберігати",
  },
  {
    infinitive: "kneel",
    past: "knelt",
    participle: "knelt",
    translation: "ставати на коліна",
  },
  {
    infinitive: "know",
    past: "knew",
    participle: "known",
    translation: "знати, бути знайомим",
  },
  {
    infinitive: "lay",
    past: "laid",
    participle: "laid",
    translation: "класти",
  },
  { infinitive: "lead", past: "led", participle: "led", translation: "вести" },
  {
    infinitive: "lean",
    past: "leant",
    participle: "leant",
    translation: "посипатися, нахилятися",
  },
  {
    infinitive: "leap",
    past: "leapt",
    participle: "leapt",
    translation: "стрибати",
  },
  {
    infinitive: "learn",
    past: "learnt",
    participle: "learnt",
    translation: "вчитися, навчати",
  },
  {
    infinitive: "leave",
    past: "left",
    participle: "left",
    translation: "залишати, покидати",
  },
  {
    infinitive: "lend",
    past: "lent",
    participle: "lent",
    translation: "позичати",
  },
  {
    infinitive: "let",
    past: "let",
    participle: "let",
    translation: "дозволяти",
  },
  { infinitive: "lie", past: "lay", participle: "lain", translation: "лежати" },
  {
    infinitive: "light",
    past: "lit",
    participle: "lit",
    translation: "запалювати",
  },
  {
    infinitive: "lose",
    past: "lost",
    participle: "lost",
    translation: "втрачати, губити",
  },
  {
    infinitive: "make",
    past: "made",
    participle: "made",
    translation: "робити, виготовляти",
  },
  {
    infinitive: "mean",
    past: "meant",
    participle: "meant",
    translation: "означати",
  },
  {
    infinitive: "meet",
    past: "met",
    participle: "met",
    translation: "зустрічати(ся)",
  },
  {
    infinitive: "overcome",
    past: "overcame",
    participle: "overcome",
    translation: "перемагати, долати",
  },
  {
    infinitive: "pay",
    past: "paid",
    participle: "paid",
    translation: "платити",
  },
  { infinitive: "put", past: "put", participle: "put", translation: "класти" },
  {
    infinitive: "read",
    past: "read",
    participle: "read",
    translation: "читати",
  },
  {
    infinitive: "ride",
    past: "rode",
    participle: "ridden",
    translation: "їздити (верхом)",
  },
  {
    infinitive: "ring",
    past: "rang",
    participle: "rung",
    translation: "дзвонити",
  },
  {
    infinitive: "rise",
    past: "rose",
    participle: "risen",
    translation: "підніматися",
  },
  { infinitive: "run", past: "ran", participle: "run", translation: "бігти" },
  {
    infinitive: "saw",
    past: "sawed",
    participle: "sawn",
    translation: "пиляти",
  },
  {
    infinitive: "say",
    past: "said",
    participle: "said",
    translation: "казати",
  },
  { infinitive: "see", past: "saw", participle: "seen", translation: "бачити" },
  {
    infinitive: "seek",
    past: "sought",
    participle: "sought",
    translation: "шукати",
  },
  {
    infinitive: "sell",
    past: "sold",
    participle: "sold",
    translation: "продавати",
  },
  {
    infinitive: "send",
    past: "sent",
    participle: "sent",
    translation: "надсилати",
  },
  {
    infinitive: "set",
    past: "set",
    participle: "set",
    translation: "ставити, налаштовувати",
  },
  { infinitive: "sew", past: "sewed", participle: "sewn", translation: "шити" },
  {
    infinitive: "shake",
    past: "shook",
    participle: "shaken",
    translation: "трясти",
  },
  {
    infinitive: "shear",
    past: "sheared",
    participle: "shorn",
    translation: "стригти",
  },
  {
    infinitive: "shine",
    past: "shone",
    participle: "shone",
    translation: "світити, сяяти",
  },
  {
    infinitive: "shoot",
    past: "shot",
    participle: "shot",
    translation: "стріляти",
  },
  {
    infinitive: "show",
    past: "showed",
    participle: "shown",
    translation: "показувати",
  },
  {
    infinitive: "shrink",
    past: "shrank",
    participle: "shrunk",
    translation: "скорочуватися, стискатися",
  },
  {
    infinitive: "shut",
    past: "shut",
    participle: "shut",
    translation: "закривати",
  },
  {
    infinitive: "sing",
    past: "sang",
    participle: "sung",
    translation: "співати",
  },
  {
    infinitive: "sink",
    past: "sank",
    participle: "sunk",
    translation: "тонути",
  },
  { infinitive: "sit", past: "sat", participle: "sat", translation: "сидіти" },
  {
    infinitive: "sleep",
    past: "slept",
    participle: "slept",
    translation: "спати",
  },
  {
    infinitive: "slide",
    past: "slid",
    participle: "slid",
    translation: "ковзати",
  },
  {
    infinitive: "smell",
    past: "smelt",
    participle: "smelt",
    translation: "нюхати, пахнути",
  },
  {
    infinitive: "sow",
    past: "sowed",
    participle: "sown",
    translation: "сіяти",
  },
  {
    infinitive: "speak",
    past: "spoke",
    participle: "spoken",
    translation: "говорити",
  },
  {
    infinitive: "speed",
    past: "sped",
    participle: "sped",
    translation: "швидко рухатися, прискорюватися",
  },
  {
    infinitive: "spell",
    past: "spelt",
    participle: "spelt",
    translation: "писати по літерах, вимовляти по буквах",
  },
  {
    infinitive: "spend",
    past: "spent",
    participle: "spent",
    translation: "витрачати, проводити час",
  },
  {
    infinitive: "spill",
    past: "spilt",
    participle: "spilt",
    translation: "розливати",
  },
  {
    infinitive: "spit",
    past: "spat",
    participle: "spat",
    translation: "плювати",
  },
  {
    infinitive: "split",
    past: "split",
    participle: "split",
    translation: "розколювати, ділити",
  },
  {
    infinitive: "spoil",
    past: "spoilt",
    participle: "spoilt",
    translation: "псувати(ся)",
  },
  {
    infinitive: "spread",
    past: "spread",
    participle: "spread",
    translation: "розповсюджувати, розстеляти",
  },
  {
    infinitive: "stand",
    past: "stood",
    participle: "stood",
    translation: "стояти",
  },
  {
    infinitive: "steal",
    past: "stole",
    participle: "stolen",
    translation: "красти",
  },
  {
    infinitive: "stick",
    past: "stuck",
    participle: "stuck",
    translation: "липнути, прикріплювати",
  },
  {
    infinitive: "sting",
    past: "stung",
    participle: "stung",
    translation: "жалити, кусати",
  },
  {
    infinitive: "stink",
    past: "stank",
    participle: "stunk",
    translation: "погано пахнути",
  },
  {
    infinitive: "strike",
    past: "struck",
    participle: "struck",
    translation: "вдаряти, бити",
  },
  {
    infinitive: "strive",
    past: "strove",
    participle: "striven",
    translation: "прагнути, старатися",
  },
  {
    infinitive: "swear",
    past: "swore",
    participle: "sworn",
    translation: "клястися",
  },
  {
    infinitive: "sweep",
    past: "swept",
    participle: "swept",
    translation: "мести",
  },
  {
    infinitive: "swim",
    past: "swam",
    participle: "swum",
    translation: "плавати",
  },
  {
    infinitive: "swing",
    past: "swung",
    participle: "swung",
    translation: "гойдатися",
  },
  {
    infinitive: "take",
    past: "took",
    participle: "taken",
    translation: "брати",
  },
  {
    infinitive: "teach",
    past: "taught",
    participle: "taught",
    translation: "вчити, навчати",
  },
  {
    infinitive: "tear",
    past: "tore",
    participle: "torn",
    translation: "рвати(ся)",
  },
  {
    infinitive: "tell",
    past: "told",
    participle: "told",
    translation: "розповідати, казати",
  },
  {
    infinitive: "think",
    past: "thought",
    participle: "thought",
    translation: "думати",
  },
  {
    infinitive: "throw",
    past: "threw",
    participle: "thrown",
    translation: "кидати",
  },
  {
    infinitive: "tread",
    past: "trod",
    participle: "trodden",
    translation: "ступати, топтати",
  },
  {
    infinitive: "undergo",
    past: "underwent",
    participle: "undergone",
    translation: "піддаватися, переживати",
  },
  {
    infinitive: "understand",
    past: "understood",
    participle: "understood",
    translation: "розуміти",
  },
  {
    infinitive: "upset",
    past: "upset",
    participle: "upset",
    translation: "розстроювати, засмучувати",
  },
  {
    infinitive: "wake",
    past: "woke",
    participle: "woken",
    translation: "прокидатися",
  },
  {
    infinitive: "wear",
    past: "wore",
    participle: "worn",
    translation: "носити (одяг)",
  },
  {
    infinitive: "weave",
    past: "wove",
    participle: "woven",
    translation: "ткати, плести",
  },
  {
    infinitive: "weep",
    past: "wept",
    participle: "wept",
    translation: "плакати",
  },
  {
    infinitive: "win",
    past: "won",
    participle: "won",
    translation: "вигравати",
  },
  {
    infinitive: "wind",
    past: "wound",
    participle: "wound",
    translation: "крутити, намотувати",
  },
  {
    infinitive: "withdraw",
    past: "withdrew",
    participle: "withdrawn",
    translation: "вилучати, відступати",
  },
  {
    infinitive: "wring",
    past: "wrung",
    participle: "wrung",
    translation: "скручувати",
  },
  {
    infinitive: "write",
    past: "wrote",
    participle: "written",
    translation: "писати",
  },
];
