export const mustHaveIrregularVerbs = [
  {
    infinitive: "be",
    past: "was/were",
    participle: "been",
    translation: "бути",
  },
  {
    infinitive: "become",
    past: "became",
    participle: "become",
    translation: "ставати",
  },
  {
    infinitive: "begin",
    past: "began",
    participle: "begun",
    translation: "починати",
  },
  {
    infinitive: "break",
    past: "broke",
    participle: "broken",
    translation: "ламати",
  },
  {
    infinitive: "bring",
    past: "brought",
    participle: "brought",
    translation: "приносити",
  },
  {
    infinitive: "build",
    past: "built",
    participle: "built",
    translation: "будувати",
  },
  {
    infinitive: "buy",
    past: "bought",
    participle: "bought",
    translation: "купувати",
  },
  {
    infinitive: "catch",
    past: "caught",
    participle: "caught",
    translation: "ловити",
  },
  {
    infinitive: "choose",
    past: "chose",
    participle: "chosen",
    translation: "обирати",
  },
  {
    infinitive: "come",
    past: "came",
    participle: "come",
    translation: "приходити",
  },
  {
    infinitive: "cost",
    past: "cost",
    participle: "cost",
    translation: "коштувати",
  },
  { infinitive: "cut", past: "cut", participle: "cut", translation: "різати" },
  { infinitive: "do", past: "did", participle: "done", translation: "робити" },
  {
    infinitive: "draw",
    past: "drew",
    participle: "drawn",
    translation: "малювати",
  },
  {
    infinitive: "drink",
    past: "drank",
    participle: "drunk",
    translation: "пити",
  },
  {
    infinitive: "drive",
    past: "drove",
    participle: "driven",
    translation: "керувати",
  },
  { infinitive: "eat", past: "ate", participle: "eaten", translation: "їсти" },
  {
    infinitive: "fall",
    past: "fell",
    participle: "fallen",
    translation: "падати",
  },
  {
    infinitive: "feel",
    past: "felt",
    participle: "felt",
    translation: "відчувати",
  },
  {
    infinitive: "find",
    past: "found",
    participle: "found",
    translation: "знаходити",
  },
  {
    infinitive: "fly",
    past: "flew",
    participle: "flown",
    translation: "літати",
  },
  {
    infinitive: "forget",
    past: "forgot",
    participle: "forgotten",
    translation: "забувати",
  },
  {
    infinitive: "forgive",
    past: "forgave",
    participle: "forgiven",
    translation: "пробачати",
  },
  {
    infinitive: "get",
    past: "got",
    participle: "got/gotten",
    translation: "отримувати",
  },
  {
    infinitive: "give",
    past: "gave",
    participle: "given",
    translation: "давати",
  },
  { infinitive: "go", past: "went", participle: "gone", translation: "йти" },
  {
    infinitive: "grow",
    past: "grew",
    participle: "grown",
    translation: "рости",
  },
  { infinitive: "have", past: "had", participle: "had", translation: "мати" },
  {
    infinitive: "hear",
    past: "heard",
    participle: "heard",
    translation: "чути",
  },
  {
    infinitive: "hide",
    past: "hid",
    participle: "hidden",
    translation: "ховати",
  },
  { infinitive: "hit", past: "hit", participle: "hit", translation: "вдаряти" },
  {
    infinitive: "hold",
    past: "held",
    participle: "held",
    translation: "тримати",
  },
  {
    infinitive: "hurt",
    past: "hurt",
    participle: "hurt",
    translation: "поранити / боліти",
  },
  {
    infinitive: "keep",
    past: "kept",
    participle: "kept",
    translation: "тримати / зберігати",
  },
  {
    infinitive: "know",
    past: "knew",
    participle: "known",
    translation: "знати",
  },
  {
    infinitive: "learn",
    past: "learned/learnt",
    participle: "learned/learnt",
    translation: "вчити / дізнаватися",
  },
  {
    infinitive: "leave",
    past: "left",
    participle: "left",
    translation: "залишати",
  },
  {
    infinitive: "lend",
    past: "lent",
    participle: "lent",
    translation: "позичати (давати в борг)",
  },
  {
    infinitive: "let",
    past: "let",
    participle: "let",
    translation: "дозволяти",
  },
  {
    infinitive: "lose",
    past: "lost",
    participle: "lost",
    translation: "втрачати",
  },
  {
    infinitive: "make",
    past: "made",
    participle: "made",
    translation: "робити / створювати",
  },
  {
    infinitive: "mean",
    past: "meant",
    participle: "meant",
    translation: "означати",
  },
  {
    infinitive: "meet",
    past: "met",
    participle: "met",
    translation: "зустрічати",
  },
  {
    infinitive: "pay",
    past: "paid",
    participle: "paid",
    translation: "платити",
  },
  { infinitive: "put", past: "put", participle: "put", translation: "класти" },
  {
    infinitive: "read",
    past: "read",
    participle: "read",
    translation: "читати",
  },
  {
    infinitive: "ride",
    past: "rode",
    participle: "ridden",
    translation: "їхати верхи / кататися",
  },
  {
    infinitive: "ring",
    past: "rang",
    participle: "rung",
    translation: "дзвонити",
  },
  { infinitive: "run", past: "ran", participle: "run", translation: "бігти" },
  {
    infinitive: "say",
    past: "said",
    participle: "said",
    translation: "казати",
  },
  { infinitive: "see", past: "saw", participle: "seen", translation: "бачити" },
  {
    infinitive: "sell",
    past: "sold",
    participle: "sold",
    translation: "продавати",
  },
  {
    infinitive: "send",
    past: "sent",
    participle: "sent",
    translation: "надсилати",
  },
  {
    infinitive: "set",
    past: "set",
    participle: "set",
    translation: "встановлювати",
  },
  {
    infinitive: "show",
    past: "showed",
    participle: "shown",
    translation: "показувати",
  },
  { infinitive: "sit", past: "sat", participle: "sat", translation: "сидіти" },
  {
    infinitive: "sleep",
    past: "slept",
    participle: "slept",
    translation: "спати",
  },
  {
    infinitive: "speak",
    past: "spoke",
    participle: "spoken",
    translation: "говорити",
  },
  {
    infinitive: "spend",
    past: "spent",
    participle: "spent",
    translation: "витрачати",
  },
  {
    infinitive: "stand",
    past: "stood",
    participle: "stood",
    translation: "стояти",
  },
  {
    infinitive: "take",
    past: "took",
    participle: "taken",
    translation: "брати",
  },
  {
    infinitive: "teach",
    past: "taught",
    participle: "taught",
    translation: "викладати",
  },
  {
    infinitive: "tell",
    past: "told",
    participle: "told",
    translation: "розповідати",
  },
  {
    infinitive: "think",
    past: "thought",
    participle: "thought",
    translation: "думати",
  },
  {
    infinitive: "throw",
    past: "threw",
    participle: "thrown",
    translation: "кидати",
  },
  {
    infinitive: "understand",
    past: "understood",
    participle: "understood",
    translation: "розуміти",
  },
  {
    infinitive: "wear",
    past: "wore",
    participle: "worn",
    translation: "носити (одяг)",
  },
  {
    infinitive: "win",
    past: "won",
    participle: "won",
    translation: "вигравати",
  },
  {
    infinitive: "write",
    past: "wrote",
    participle: "written",
    translation: "писати",
  },
];
